export enum ConversationState {
  NEW = "NEW",
  WAITING_NAME = "WAITING_NAME",
  WAITING_ADDRESS = "WAITING_ADDRESS",
  WAITING_PHONE = "WAITING_PHONE",
  REGISTERED = "REGISTERED",
  MENU = "MENU",
  ORDER = "ORDER",
}